# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'win.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(1024, 577)
        Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Frame)
        self.frame.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame.setStyleSheet("border:2px solid rgb(0,0,255)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.start_but = QtWidgets.QPushButton(self.frame)
        self.start_but.setMaximumSize(QtCore.QSize(16777215, 45))
        self.start_but.setObjectName("start_but")
        self.verticalLayout.addWidget(self.start_but)
        self.stop_but = QtWidgets.QPushButton(self.frame)
        self.stop_but.setMaximumSize(QtCore.QSize(16777215, 45))
        self.stop_but.setObjectName("stop_but")
        self.verticalLayout.addWidget(self.stop_but)
        self.exit_but = QtWidgets.QPushButton(self.frame)
        self.exit_but.setMaximumSize(QtCore.QSize(16777215, 45))
        self.exit_but.setObjectName("exit_but")
        self.verticalLayout.addWidget(self.exit_but)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(Frame)
        self.frame_2.setStyleSheet("border:2px solid rgb(0,0,255)")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.labCamera = QtWidgets.QLabel(self.frame_2)
        self.labCamera.setGeometry(QtCore.QRect(1, -6, 741, 561))
        self.labCamera.setText("")
        self.labCamera.setObjectName("labCamera")
        self.horizontalLayout.addWidget(self.frame_2)

        self.retranslateUi(Frame)
        self.start_but.clicked.connect(Frame.but_start_click)
        self.stop_but.clicked.connect(Frame.but_stop_click)
        self.exit_but.clicked.connect(Frame.but_quit_click)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.start_but.setText(_translate("Frame", "开始播放"))
        self.stop_but.setText(_translate("Frame", "停止播放"))
        self.exit_but.setText(_translate("Frame", "退出"))


